### ISSUE TITLE
Wrong P2 repository for Third party module

### ISSUE THREAD

**Issue by claudio-rosati** [ControlSystemStudio/org.csstudio.docbook#1]
Inside the chapter [P2 Repositories](http://cs-studio.sourceforge.net/docbook/ch04.html#idp113664), the path of the local repository for the _Third party_ module is `diirt/repository/target/repository` instead of `cs-studio-thirdparty/repository/target/repository`.

**Comment by kasemir** [comment]
Thanks! See 678f18d4a100b4ff3f58d6ee342c03142d6faa02

Yes, diirt uses a slightly different path (with "p2"). And its own version numbering. And its own configuration files, which I'd rather replace than document.

**Comment by claudio-rosati** [comment]
Now my compositeArtifacts.xml and compositeContent.xml are the ones inside [ess_css_comp_repo.zip](https://github.com/ControlSystemStudio/org.csstudio.docbook/files/316336/ess_css_comp_repo.zip).

When I try to execute the following command from [Configuring and Invoking Maven](http://cs-studio.sourceforge.net/docbook/ch04.html#idp186064):

> `(cd cs-studio-thirdparty; mvn clean verify)`

I have the errors reported in [error.txt](https://github.com/ControlSystemStudio/org.csstudio.docbook/files/316352/error.txt)

Can you help me?

Claudio

**Comment by kasemir** [comment]
Looks like your error is "No repository found at file:/Users/claudiorosati/Projects/GitHub/cs-studio-thirdparty/repository/target/repository".

In your composite repo, check the "p2.atomic.composite.loading". Read the comments on the files in https://github.com/ControlSystemStudio/org.csstudio.sns/tree/master/css_repo where I set that to false because when I start out from scratch, cs-studio-thirdparty/repository/target/repository is empty, since I yet have to build it.

**Comment by claudio-rosati** [comment]
OK, this is different from what written in [Composite P2 Repository](http://cs-studio.sourceforge.net/docbook/ch04.html#idp157632), where the compositeArtifacts.xml example has no "p2.atomic.composite.loading" property set. So I suggest to update it too.

Anyway, now is working, thank you.

Claudio

**Comment by kasemir** [comment]
I was never sure if that's needed in both of those XML files. I've updated the doc.
