### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by claudio-rosati** [ControlSystemStudio/org.csstudio.docbook#2]
When executing the instruction at [Configuring and Invoking Maven](http://cs-studio.sourceforge.net/docbook/ch04.html#idp201776) to build the _cs-studio/applications_ the following error appeared: `java.lang.OutOfMemoryError: GC overhead limit exceeded`.

Trying different solutions, the only one that worked fine was adding following line to my _.profile_:

> `export MAVEN_OPTS='-Xmx2048m -Xms1024M -Xss128M -XX:-UseGCOverheadLimit'`
> that is, increasing the memory heap space and, more important, disabling the garbage collector's overhead limit.

I think that a note about it can be inserted in the Configuring and Invoking Maven](http://cs-studio.sourceforge.net/docbook/ch04.html#idp201776) section, or just before, where there is the explanation about setting the `JAVA_HOME` and `PATH` environment variables.

**Comment by kasemir** [comment]
Actually, I'd prefer to require some basic understanding of Java, because we cannot repeat the Java documentation, including its updates.

An out of memory error and how to overcome it for the various versions of Java is well documented and the information can be obtained via a google search.

**Comment by claudio-rosati** [comment]
The problem is with Maven configuration more tha Java itself. But I understand your point: at the end googling for the error will tell you how to overcome the problem.

**Comment by kasemir** [comment]
Exactly. Plus I consider the move to Maven a really unfortunate event. Not really our fault because Eclipse itself moves to maven/tycho, and at times the original headless build and 'product export' from the IDE were broken for Eclipse 4.x. Still, what a royal pain in the eyebrow how even a "mvn clean" starts by downloading the internet and then potentially fails with a timeout, while "ant clean" simply removed the build directories.
Anyway, the world may disagree with me on maven, but the world can't force me to waste even more time documenting this crap.

On the plugin_customization location, #3, feel free to submit a pull request for a documentation update if you think it's worthwhile.
